scripts:
  - name: Generate Android platform files
    script: |
      rm -rf android
      flutter create --platforms=android --overwrite .
      ls -la android
  - name: Get Flutter packages
    script: |
      flutter pub get
  - name: Build APK
    script: |
      flutter build apk --release